version: '3'
services:
  wayni_app:
    container_name: wayni_app
    image: webdevops/php-nginx-dev:7.4
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=-1
      # - XDEBUG_MODE=debug
      # - XDEBUG_START_WITH_REQUEST=yes
      # - XDEBUG_CLIENT_PORT=9000
      # - XDEBUG_CLIENT_HOST=host.docker.internal
      # - XDEBUG_MAX_NESTING_LEVEL=1000
    ports:
      - "2912:80"
    volumes:
      - ./:/app:rw,cached